/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DemoAppMsgL'
 * message type.
 */

public class DemoAppMsgL extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 131;

    /** Create a new DemoAppMsgL of size 2. */
    public DemoAppMsgL() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DemoAppMsgL of the given data_length. */
    public DemoAppMsgL(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL with the given data_length
     * and base offset.
     */
    public DemoAppMsgL(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL using the given byte array
     * as backing store.
     */
    public DemoAppMsgL(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL using the given byte array
     * as backing store, with the given base offset.
     */
    public DemoAppMsgL(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DemoAppMsgL(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL embedded in the given message
     * at the given base offset.
     */
    public DemoAppMsgL(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgL embedded in the given message
     * at the given base offset and length.
     */
    public DemoAppMsgL(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DemoAppMsgL> \n";
      try {
        s += "  [lReading=0x"+Long.toHexString(get_lReading())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: lReading
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'lReading' is signed (false).
     */
    public static boolean isSigned_lReading() {
        return false;
    }

    /**
     * Return whether the field 'lReading' is an array (false).
     */
    public static boolean isArray_lReading() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'lReading'
     */
    public static int offset_lReading() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'lReading'
     */
    public static int offsetBits_lReading() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'lReading'
     */
    public int get_lReading() {
        return (int)getUIntBEElement(offsetBits_lReading(), 16);
    }

    /**
     * Set the value of the field 'lReading'
     */
    public void set_lReading(int value) {
        setUIntBEElement(offsetBits_lReading(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'lReading'
     */
    public static int size_lReading() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'lReading'
     */
    public static int sizeBits_lReading() {
        return 16;
    }

}
