/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'DemoAppMsgH'
 * message type.
 */

public class DemoAppMsgH extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 2;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 132;

    /** Create a new DemoAppMsgH of size 2. */
    public DemoAppMsgH() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new DemoAppMsgH of the given data_length. */
    public DemoAppMsgH(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH with the given data_length
     * and base offset.
     */
    public DemoAppMsgH(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH using the given byte array
     * as backing store.
     */
    public DemoAppMsgH(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH using the given byte array
     * as backing store, with the given base offset.
     */
    public DemoAppMsgH(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public DemoAppMsgH(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH embedded in the given message
     * at the given base offset.
     */
    public DemoAppMsgH(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new DemoAppMsgH embedded in the given message
     * at the given base offset and length.
     */
    public DemoAppMsgH(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <DemoAppMsgH> \n";
      try {
        s += "  [hReading=0x"+Long.toHexString(get_hReading())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: hReading
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'hReading' is signed (false).
     */
    public static boolean isSigned_hReading() {
        return false;
    }

    /**
     * Return whether the field 'hReading' is an array (false).
     */
    public static boolean isArray_hReading() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'hReading'
     */
    public static int offset_hReading() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'hReading'
     */
    public static int offsetBits_hReading() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'hReading'
     */
    public int get_hReading() {
        return (int)getUIntBEElement(offsetBits_hReading(), 16);
    }

    /**
     * Set the value of the field 'hReading'
     */
    public void set_hReading(int value) {
        setUIntBEElement(offsetBits_hReading(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'hReading'
     */
    public static int size_hReading() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'hReading'
     */
    public static int sizeBits_hReading() {
        return 16;
    }

}
